<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>ClientLoaderTestPlugin</AssemblyName>
    <RootNamespace>ClientLoader.TestPlugin</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnityPluginLoader\UnityPluginLoader.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Librairies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>..\Librairies\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\Librairies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Librairies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\Librairies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
